import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PageAnimatePresence from "./PageAnimatePresence";
import Inner from "./Inner";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageAnimatePresence>
          <Inner>
            <header className="flex flex-row gap-5 items-center justify-center p-7">
              <Link href="/">Home</Link>
              <Link href="/contact">Contact</Link>
              <Link href="/issues">Issues</Link>
            </header>
            {children}
          </Inner>
        </PageAnimatePresence>
      </body>
    </html>
  );
}
